---
- hosts: localhost
  module_defaults:
    group/k8s:
      host: "https://api.{{ openshift_cluster_fqdn }}:6443"
      username: "{{ openshift_cluster_admin_username }}"
      password: "{{ openshift_cluster_admin_password }}"
      validate_certs: no

  vars:
    kubeadmin_password: "{{ lookup('file', '{{ openshift_build_path }}/auth/kubeadmin-password') }}"


  tasks:
    - name: create cluster admin and user accounts
      include_role:
        name: create_openshift_users
      when: create_openshift_users == true
    - name: deploy web terminal
      include_role:
        name: deploy_web_terminal
      when: deploy_web_terminal == true
    - name: serverless
      include_role:
        name: deploy_serverless
      when: deploy_serverless == true
    - name: deploy openshift service mesh
      include_role:
        name: deploy_service_mesh
      when: deploy_service_mesh == true

    - name: deploy and configure openshift workshop resources
      include_role:
        name: deploy_service_mesh_workshop
      when: deploy_service_mesh_workshop == true


