---
- name: Force Monitoring Cert rotation
  hosts: localhost
  become: no
  gather_facts: false
  environment:
    KUBECONFIG: /home/{{ user }}/{{ cluster_name }}/auth/kubeconfig
  tasks:
  - name: Get Config Map Definition
    shell: oc get configmap extension-apiserver-authentication -n kube-system -o yaml >/tmp/extension-apiserver-authentication.yaml
  - name: Add an empty line to config map file
    lineinfile:
      path: /tmp/extension-apiserver-authentication.yaml
      firstmatch: true
      insertafter: '-----END CERTIFICATE-----'
      line: ''
  - name: Update Config Map with new file
    k8s:
      state: present
      src: /tmp/extension-apiserver-authentication.yaml
