---

- name: Check to see if requisite repos are already enabled (rhel 8)
  become: yes
  shell: subscription-manager repos --list-enabled | egrep 'rhel-8-for-x86_64-baseos-rpms|rhel-8-for-x86_64-appstream-rpms' | wc -l
  register: smr_result
  ignore_errors: True
  tags:
    - rhel

- name: Disable all repos by default (rhel 8)
  command: subscription-manager repos --disable "*"
  when: smr_result.stdout != "2"
  tags:
    - rhel

- name: Enable the requisite repos (rhel 8)
  shell: subscription-manager repos --enable="rhel-8-for-x86_64-baseos-rpms" --enable="rhel-8-for-x86_64-appstream-rpms" 
  when: smr_result.stdout != "2"
  tags:
    - rhel

...
